spring:
  jpa:
    database: postgresql
    open-in-view: true
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/jira
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
server:
  port: 8080

